ConferenceRoomReservation/alpha/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('reservation_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ConferenceRoomReservation/reservation_app/urls.py
from django.urls import path
from . import views as reservation_views

app_name = 'reservation_app'

urlpatterns = [
    path('home/', reservation_views.home_view, name="home"),
    path('room/new/', reservation_views.AddRoomView.as_view(), name="add-room"),
    path('', reservation_views.RoomListView.as_view(), name="room-list"),
    path('room/delete/<int:room_id>/', reservation_views.DeleteRoomView.as_view(), name="delete-room"),
    path('room/modify/<int:room_id>/', reservation_views.ModifyRoomView.as_view(), name="modify-room"),
    path('room/book/<int:room_id>/', reservation_views.ReservationView.as_view(), name="book-room"),
    path('room/<int:room_id>/', reservation_views.RoomDetailsView.as_view(), name="room"),
    path('search/', reservation_views.SearchView.as_view(), name="room-list"),

]

ConferenceRoomReservation/reservation_app/models.py
from django.db import models


# Create your models here.
class ConferenceRoom(models.Model):
    name = models.CharField(max_length=255, unique=True)
    capacity = models.PositiveIntegerField()
    projector_availability = models.BooleanField(default=False)


class RoomReservation(models.Model):
    room_id = models.ForeignKey(ConferenceRoom, on_delete=models.CASCADE)
    date = models.DateField(blank=True, null=True)
    comment = models.TextField(null=True)

    class Meta:
        unique_together = ('room_id', 'date',)

ConferenceRoomReservation/reservation_app/views.py
from django.shortcuts import render, redirect
from django.views import View
from .models import ConferenceRoom, RoomReservation

import datetime


# Create your views here.


def home_view(request):
    return render(request, 'reservation_app/base.html')


class AddRoomView(View):
    def get(self, request):
        return render(request, 'reservation_app/add_room.html')

    def post(self, request):
        name = request.POST.get("room-name")
        capacity = request.POST.get("capacity")
        capacity = int(capacity) if capacity else 0
        projector = request.POST.get("projector") == "on"

        if not name:
            return render(request, 'reservation_app/add_room.html', context={"error": "Nie podano nawy sali"})
        if capacity <= 0:
            return render(request, 'reservation_app/add_room.html', context={"error": "Pojemność sali musi być dodatnia"})
        if ConferenceRoom.objects.filter(name=name).first():
            return render(request, 'reservation_app/add_room.html',
                          context={"error": "Sala o podanej nazwie istnieje"})

        ConferenceRoom.objects.create(name=name, capacity=capacity, projector_availability=projector)
        return redirect("reservation_app:room-list")


class RoomListView(View):
    def get(self, request):
        rooms = ConferenceRoom.objects.all()
        for room in rooms:
            reservation_dates = [reservation.date for reservation in room.roomreservation_set.all()]
            room.reserved = datetime.date.today() in reservation_dates
        return render(request, "reservation_app/rooms.html", context={"rooms": rooms})


class DeleteRoomView(View):
    def get(self, request, room_id):
        room = ConferenceRoom.objects.filter(id=room_id)
        room.delete()
        return redirect("reservation_app:room-list")


class ModifyRoomView(View):
    def get(self, request, room_id):
        room = ConferenceRoom.objects.get(id=room_id)
        return render(request, "reservation_app/modify_room.html", context={"room": room})

    def post(self, request, room_id):
        room = ConferenceRoom.objects.get(id=room_id)
        name = request.POST.get("room-name")
        capacity = request.POST.get("capacity")
        capacity = int(capacity) if capacity else 0
        projector = request.POST.get("projector") == "on"

        if not name:
            return render(request, "reservation_app/modify_room.html", context={"room": room,
                                                                "error": "Nie podano nawy sali"})
        if capacity <= 0:
            return render(request, "reservation_app/modify_room.html", context={"room": room,
                                                                "error": "Pojemność sali musi być dodatnia"})
        if name != room.name and ConferenceRoom.objects.filter(name=name).first():
            return render(request, "reservation_app/modify_room.html", context={"room": room,
                                                                "error": "Sala o podanej nazwie istnieje"})

        room.name = name
        room.capacity = capacity
        room.projector_availability = projector
        room.save()
        return redirect("reservation_app:room-list")


class ReservationView(View):
    def get(self, request, room_id):
        room = ConferenceRoom.objects.get(id=room_id)
        reservations = room.roomreservation_set.filter(date__gte=str(datetime.date.today())).order_by('date')
        return render(request, "reservation_app/reservation.html", context={"room": room, "reservations": reservations})

    def post(self, request, room_id):
        room = ConferenceRoom.objects.get(id=room_id)
        date = request.POST.get("reservation-date")
        comment = request.POST.get("comment")

        reservations = room.roomreservation_set.filter(date__gte=str(datetime.date.today())).order_by('date')

        if RoomReservation.objects.filter(room_id=room, date=date):
            return render(request, "reservation_app/reservation.html", context={"room": room,
                                                                                "reservations": reservations,
                                                                                "error": "Sala jest już zarezerwowana!"})
        if date < str(datetime.date.today()):
            return render(request, "reservation_app/reservation.html", context={"room": room,
                                                                                "reservations": reservations,
                                                                                "error": "Data jest z przeszłości!"})

        RoomReservation.objects.create(room_id=room, date=date, comment=comment)
        return redirect("reservation_app:room-list")


class RoomDetailsView(View):
    def get(self, request, room_id):
        room = ConferenceRoom.objects.get(id=room_id)
        reservations = room.roomreservation_set.filter(date__gte=str(datetime.date.today())).order_by('date')
        return render(request, "reservation_app/room_details.html", context={"room": room, "reservations": reservations})


class SearchView(View):
    def get(self, request):
        name = request.GET.get("room-name")
        capacity = request.GET.get("capacity")
        capacity = int(capacity) if capacity else 0
        projector = request.GET.get("projector") == "on"

        rooms = ConferenceRoom.objects.all()
        if projector:
            rooms = rooms.filter(projector_availability=projector)
        if capacity:
            rooms = rooms.filter(capacity__gte=capacity)
        if name:
            rooms.filter(name__contains=name)

        for room in rooms:
            reservation_dates = [reservation.date for reservation in room.roomreservation_set.all()]
            room.reserved = str(datetime.date.today()) in reservation_dates

        return render(request, "reservation_app/rooms.html", context={"rooms": rooms, "date": datetime.date.today()})

ConferenceRoomReservation/reservation_app/templates/reservation_app/add_room.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Home Page</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/sticky-footer/">
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <style>
    .footer {
      position: absolute;
      bottom: 0;
      width: 100%;
      height: 60px; /* Set the fixed height of the footer here */
      line-height: 60px; /* Vertically center the text there */
      background-color: #f5f5f5;
    }
  </style>
</head>
<body>
<!-- Nav -->
<nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">System rezerwacji sal</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link" href="{% url 'reservation_app:room-list' %}">Lista wszystkich sal<span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link active" href="{% url 'reservation_app:add-room' %}">Dodaj salę</a>
    </div>
  </div>
</nav>
<!-- Nav -->

<!-- Form -->
<div class="card">
  <div class="card-body">
    <form action="" method="POST">
      {% csrf_token %}
      <div class="form-group">
        <label for="room-name">Nazwa sali</label>
        <input type="text" class="form-control" id="room-name" aria-describedby="room-name-help" placeholder="Nazwa sali" name="room-name">
        <small id="room-name-help" class="form-text text-muted">Nazwa sali musi być unikatowa.</small>
      </div>
      <div class="form-group">
        <label for="capacity">Pojemność sali</label>
        <input type="number" step="1" class="form-control" id="capacity" placeholder="10" name="capacity">
      </div>
      <div class="form-check">
        <input type="checkbox" class="form-check-input" name="projector" id="projector">
        <label class="form-check-label" for="projector">Dostępność rzutnika</label>
      </div>
      <button type="submit" class="btn btn-primary">Dodaj salę</button>
    </form>
  </div>
</div>
<!-- Form -->

{% if error %}
<!-- Form error -->
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  {{error}}
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<!-- Form error -->
{% endif %}

<!-- Footer -->
<footer class="footer">
      <div class="container">
        <span class="text-muted">Darth Vader</span>
      </div>
    </footer>
<!-- Footer -->
</body>
</html>

ConferenceRoomReservation/reservation_app/templates/reservation_app/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Room Reservation App</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
  </head>
  <body>
    <h1>Hello, world!</h1>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
  </body>
</html>

ConferenceRoomReservation/reservation_app/templates/reservation_app/modify_room.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Home Page</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/sticky-footer/">
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <style>
    .footer {
      position: absolute;
      bottom: 0;
      width: 100%;
      height: 60px; /* Set the fixed height of the footer here */
      line-height: 60px; /* Vertically center the text there */
      background-color: #f5f5f5;
    }
  </style>
</head>
<body>
<!-- Nav -->
<nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">System rezerwacji sal</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
        <a class="nav-item nav-link active" href="{% url 'reservation_app:room-list' %}">Lista wszystkich sal<span class="sr-only">(current)</span></a>
         <a class="nav-item nav-link" href="{% url 'reservation_app:add-room' %}">Dodaj salę</a>
    </div>
  </div>
</nav>
<!-- Nav -->

<!-- Form -->
<div class="card">
  <div class="card-body">
    <form action="" method="POST">
      {% csrf_token %}
      <div class="form-group">
        <label for="room-name">Nazwa sali</label>
        <input type="text" class="form-control" id="room-name" aria-describedby="room-name-help" placeholder="Nazwa sali" name="room-name" value="{{ room.name }}">
        <small id="room-name-help" class="form-text text-muted">Nazwa sali musi być unikatowa.</small>
      </div>
      <div class="form-group">
        <label for="capacity">Pojemność sali</label>
        <input type="number" step="1" class="form-control" id="capacity" placeholder="10" name="capacity" value="{{ room.capacity }}">
      </div>
      <div class="form-check">
        <input type="checkbox" class="form-check-input" name="projector" id="projector" {% if room.projector_availability %} checked {% endif %}>
        <label class="form-check-label" for="projector">Dostępność rzutnika</label>
      </div>
      <button type="submit" class="btn btn-primary">Edytuj</button>
    </form>
  </div>
</div>
<!-- Form -->

{% if error %}
<!-- Form error -->
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  {{error}}
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<!-- Form error -->
{% endif %}

<!-- Footer -->
<footer class="footer">
      <div class="container">
        <span class="text-muted">Darth Vader</span>
      </div>
    </footer>
<!-- Footer -->
</body>
</html>

ConferenceRoomReservation/reservation_app/templates/reservation_app/reservation.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Home Page</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/sticky-footer/">
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <style>
    .footer {
      position: absolute;
      bottom: 0;
      width: 100%;
      height: 60px; /* Set the fixed height of the footer here */
      line-height: 60px; /* Vertically center the text there */
      background-color: #f5f5f5;
    }
  </style>
</head>
<body>
<!-- Nav -->
<nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">System rezerwacji sal</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
        <a class="nav-item nav-link active" href="{% url 'reservation_app:room-list' %}">Lista wszystkich sal<span class="sr-only">(current)</span></a>
         <a class="nav-item nav-link" href="{% url 'reservation_app:add-room' %}">Dodaj salę</a>
    </div>
  </div>
</nav>
<!-- Nav -->

<!-- Form -->
<div class="card">
  <div class="card-body">
    <h2>Nazwa sali: {{ room.name }}</h2>
    <form action="" method="POST">
      {% csrf_token %}
      <div class="form-group">
        <label for="reservation-date">Data rezerwacji</label>
        <input type="date" id="reservation-date" name="reservation-date" max="3000-12-31"
               min="1000-01-01" class="form-control">
      </div>

      <div class="form-group">
        <label for="comment">Komentarz</label>
        <textarea class="form-control" id="comment" name="comment"></textarea>
      </div>

      <button type="submit" class="btn btn-primary">Zarezerwuj</button>
    </form>
  </div>
</div>
<!-- Form -->

{% if error %}
<!-- Form error -->
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  {{error}}
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<!-- Form error -->
{% endif %}

<!-- Wszystkie rezerwacje -->
<div class="card">
  <div class="card-body">
    <h3>Rezerwacje</h3>
    <ul class="list-group">
      {% for reservation in reservations %}
      <li class="list-group-item">
        <h4>{{ reservation.date }}</h4>
        <p>{{ reservation.comment }}</p>
      </li>
      {% endfor %}
    </ul>
  </div>
</div>
<!-- Wszystkie rezerwacje -->


<!-- Footer -->
<footer class="footer">
      <div class="container">
        <span class="text-muted">Darth Vader</span>
      </div>
    </footer>
<!-- Footer -->
</body>
</html>

ConferenceRoomReservation/reservation_app/templates/reservation_app/rooms.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Home Page</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/sticky-footer/">
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <style>
    .footer {
      position: absolute;
      bottom: 0;
      width: 100%;
      height: 60px; /* Set the fixed height of the footer here */
      line-height: 60px; /* Vertically center the text there */
      background-color: #f5f5f5;
    }
  </style>
</head>
<body>
<!-- Nav -->
<nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">System rezerwacji sal</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="{% url 'reservation_app:room-list' %}">Lista wszystkich sal<span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link" href="{% url 'reservation_app:add-room' %}">Dodaj salę</a>
    </div>
  </div>
</nav>
<!-- Nav -->

<!-- table -->
<table class="table">
  <thead>
    <tr class="d-flex">
      <th scope="col" class="col-1">#</th>
      <th scope="col" class="col-2">Nazwa</th>
      <th scope="col" class="col-1">Pojemność</th>
      <th scope="col" class="col-2">Dostępność</th>
      <th scope="col" class="col-5" colspan="4">Dostępność rzutnika</th>
    </tr>
  </thead>
  <tbody>
    {% for room in rooms %}
    <tr class="d-flex">
      <th scope="row" class="col-1">{{ room.id }}</th>
      <td class="col-2">
        <a href="/room/{{ room.id }}/">{{ room.name }}</a>
      </td>
      <td class="col-1">{{ room.capacity }}</td>
      {% if room.reserved %}
        <td class="col-2" style="color:red;">Zarezerwowana</td>
      {% else %}
        <td class="col-2" style="color:green;">Dostępna</td>
      {% endif %}
      {% if room.projector_availability %}
        <td class="col-2" style="color:green;">&#9745;</td>
      {% else %}
        <td class="col-2" style="color:red;">&#9746;</td>
      {% endif %}
      <td class="col-1">
        <a href="/room/modify/{{ room.id }}/">edytuj</a>
      </td>
      <td class="col-1">
        <a href="/room/delete/{{ room.id }}/">usuń</a>
      </td>
      <td class="col-1">
<!--        <a href="/room/reserve/{{ room.id }}/">zarezerwuj</a>-->
        <a href="{% url 'reservation_app:book-room' room.id %}">zarezerwuj</a>
      </td>
    </tr>
    {% empty %}
      <tr><td colspan="6">Brak dostępnych sal</td></tr>
    {% endfor %}
  </tbody>
</table>
<!-- table -->


<!-- Form -->
<h3>Wyszukiwanie</h3>
<div class="card">
  <div class="card-body">
    <form action="/search" method="GET">
      {% csrf_token %}
      <div class="form-group">
        <label for="room-name">Nazwa sali</label>
        <input type="text" class="form-control" id="room-name" aria-describedby="room-name-help" placeholder="Nazwa sali" name="room-name">
      </div>
      <div class="form-group">
        <label for="capacity">Minimalna pojemność sali</label>
        <input type="number" step="1" class="form-control" id="capacity" placeholder="10" name="capacity">
      </div>

      <div class="form-check">
        <input type="checkbox" class="form-check-input" name="projector" id="projector">
        <label class="form-check-label" for="projector">Dostępność rzutnika</label>
      </div>
      <button type="submit" class="btn btn-primary">Szukaj</button>
    </form>
  </div>
</div>
<!-- Form -->

<!-- Footer -->
<footer class="footer">
      <div class="container">
        <span class="text-muted">Darth Vader</span>
      </div>
    </footer>
<!-- Footer -->
</body>
</html>